### ISSUE TITLE
Enable disabling of Crunchbase lookups

### ISSUE THREAD

**Issue by coney** [cncf/landscapeapp#206]
Just a question, Can I use landscapeapp and add new entries without crunchbase api key? seems that landscapeapp will fetch informations from crunchbase using crunchbase api.
But I don't have that key right now, and crunchbase said that api access is not free.

**Comment by dankohn** [comment]
If you want to use landscapeapp for your own landscape, you would either need a Crunchbase API key or you should disable Crunchbase lookups.

**Comment by eifinger** [comment]
Just stumpled over that as well. Is there a switch to disable Crunchbase lookups or should I remove the relevant code for that?

**Comment by dankohn** [comment]
I'd encourage you to add a switch to disable Crunchbase lookups. We can do so, but it may take a while.

**Comment by dankohn** [comment]
Add a new field in settings.yml for disabling Crunchbase lookups to make it easier to fork the project for the other purposes.

**Comment by sukramlitt** [comment]
I would also be interested in this feature

**Comment by sebastianguzera** [comment]
Has anyone had luck with disabling crunchbase? I've attempted to remove the lookups in the generateJSON, but running into an issue with the UI not being able to generate locally when the crunchbase information is not present in the processed_landscape.yml. Looking for general guidance to get an idea of how tightly coupled the UI is to the crunchbase info.

**Comment by dankohn** [comment]
@AndreyKozlov1984  Please add a prominent switch that disables Crunchbase lookups.

**Comment by sebastianguzera** [comment]
@AndreyKozlov1984 anything I can do to help move this along? We have a team that would be more than happy to contribute back to the project. We just need some general guidance to get an idea of how tightly coupled the UI is to the crunchbase info.

**Comment by jordinl83** [comment]
@dankohn @sebastianguzera See the LFPH Landscape for [an example](https://github.com/lfph/lfph-landscape/blob/177e1932ecee36c3bd19f01e3c8ac1f70caba586/landscape.yml#L178-L181) that does not use a crunchbase entry. The `organization` object is used instead of the `crunchbase` URL. The FINOS landscape is also using it [this way](https://github.com/finos/finos-landscape/blob/7956765980e642465bc6bab8419eb515763f7785/landscape.yml#L9-L10)

**Comment by dankohn** [comment]
Right. But we want to add a switch to settings.yml that stops all Crunchbase lookups to make it easier for third parties without the Crunchbase key to start playing with the landscape.

**Comment by AndreyKozlov1984** [comment]
Ok, will try that approach.

**Comment by AndreyKozlov1984** [comment]
I am making a branch on FINOS project which has a set of entries without a crunchbase and will try to make it running without having anything in the processed_landscape.yml and without a crunchbase api key.

**Comment by AndreyKozlov1984** [comment]
Ok, I got it working on a finos landscape in a special branch, will test it a bit more and add a pull request

**Comment by AndreyKozlov1984** [comment]
@sebastianguzera we merged this into the master. Please, check the branch https://github.com/finos/finos-landscape/tree/test-no-crunchbase as an example of no crunchbase landscape. Also, everything you put under `organization` field , not only the `name`, is used instead of a crunchbase information, i.e. what you see in `crunchbase_data` in the `processed_landscape.yml` of a typical landscape can be used to add to the `organization` filed of any item in the `landscape.yml`
