### ISSUE TITLE
Use smaller Twitter icon

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#246]
On the iPhone, in card mode we’re showing the bigger Twitter icon. Please show the smaller one instead. 

![A19A72A4-61B3-4BE1-B607-6389F4B2D06D](https://user-images.githubusercontent.com/3083270/61438861-5e51c700-a97b-11e9-84ab-0a844f7061dd.png)

**Comment by dankohn** [comment]
@jordinl83 Could you please take this over.

**Comment by jordinl83** [comment]
@dankohn sure. Should we still show the count next to the icon? Or should the count also be hidden?

**Comment by dankohn** [comment]
If it fits than please show the count.

**Comment by jordinl83** [comment]
There seems to be a few issues with the tweet button and the zoom buttons.

On my phone (Xiaomi Redmi 4X) it looks too close to "Members" and misaligned:

<img src="https://user-images.githubusercontent.com/16135423/64233508-ab223a80-cef4-11e9-8a5d-923638e796b2.png" width="250" />

On my tablet (Huawei Mediapad) in portrait mode it looks broken:

<img src="https://user-images.githubusercontent.com/16135423/64233881-76fb4980-cef5-11e9-85e1-e49811757da0.png" width="400" />

And on my tablet in landscape mode it looks even worse because the sidebar is taking up space:

<img src="https://user-images.githubusercontent.com/16135423/64235078-e96d2900-cef7-11e9-99bb-8762ea56b906.png" width="500" />

Regarding the tweet and zoom buttons, I think there's too much in one row and making the tweet button smaller will not fix it for smaller screens.

**Comment by jordinl83** [comment]
Screenshot of iphone 5/SE emulation:

<img src="https://user-images.githubusercontent.com/16135423/64238304-7adf9980-cefe-11e9-9720-a513f312430e.png" width="250" />

**Comment by dankohn** [comment]
I'd like a complete solution, please. In the final image, I would suggest eliminating the `100%` so that everything else could fit.
