### ISSUE TITLE
Fetching start dates hangs

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#315]
Try branch `start_dates_entries_hang` on https://github.com/openmainframeproject/omp-landscape and the GitHub fetch of `yf` hangs.

I thought this was fixed by https://github.com/cncf/landscapeapp/commit/1654d81b3b91cc53277896e7d05c2fc33c397e57 but it doesn't seem to be.

Cc @jmertic

**Comment by jordinl83** [comment]
@dankohn @jmertic It certainly is working for me. Can you try again?  -- You might have to merge `master` first, to include the changes to _members_

**Comment by dankohn** [comment]
Still hanging for me. @jmertic ?

**Comment by jmertic** [comment]
Same here @dankohn

**Comment by jordinl83** [comment]
@jmertic @dankohn can you run `npm run latest` before running `yf`?

**Comment by dankohn** [comment]
@jordinl83 Please do these steps:

```sh
cd ../omp-landscape/
git pull
git checkout start_dates_entries_hang
npm run latest
grep "interactive-landscape" package.json # "interactive-landscape": "^1.0.247"
yf
```
And I see:
```
Fetching github entries
...........................Attempt # 5
```

**Comment by dankohn** [comment]
See my comment after yours.

**Comment by jordinl83** [comment]
@dankohn @jmertic there's definitely something weird going on. When I run `npm run fetch` from my local `landscapeapp` directory I don't get any issues. But If I execute `npm explore interactive-landscape -- npm run fetch` (which is `yf`) from the `omp-landscape` directory then I can reproduce the issue you're having.

Not entirely sure why this is happening, but running `rm -rf node_modules && npm install` fixed it.

Don't know if it could be caused by `package.json` pointing to the wrong repo: https://github.com/openmainframeproject/omp-landscape/blob/master/package.json

**Comment by jmertic** [comment]
I can confirm that running `rm -rf node_modules && npm install && yf` fixes this. Trying to push to production.

**Comment by jmertic** [comment]
And the build worked too!

https://app.netlify.com/sites/omp-landscape/deploys/5d6e7ce76d4e5e00081d91ee

**Comment by dankohn** [comment]
All fixed. Thanks @jordinl83.
