### ISSUE TITLE
Github markdown emoji in description not being parsed and rendered

### ISSUE THREAD

**Issue by jmertic** [cncf/landscapeapp#328]
See example at https://landscape.aswf.io/selected=py-scene-detect

**Comment by dankohn** [comment]
This is an issue with how people put information in GitHub, not a bug with the landscape, and not something that I believe we can fix. If you fork the repo and edit the description you can see that it starts with `:movie_camera:` instead of 🎥. The repo owner can edit the description and replace the former with the latter, in which case we'll correctly pick it up.

We could do the substitution ourselves using https://gist.github.com/rxaviers/7360908 but I question whether we'd keep it up to date.

**Comment by jmertic** [comment]
I get what you are saying, but thinking it's best to be accomodating since GitHub does parse the markdown emoji correctly and specifies that it can be used. Not thinking the markdown emojis are added all that often.
