### ISSUE TITLE
Logo disappears in specific circumstances

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#341]
![image](https://user-images.githubusercontent.com/3083270/64924235-4c8c7480-d7b0-11e9-9f58-772cb2f23a07.png)

1. Go to https://landscape.cncf.io/format=card-mode&project=member
2. Scroll down and see that the second Aqua logo is missing
3. Hit reload and see that it appears and then disappears.
4. Right-click on the missing logo and choose Inspect. See that it partially appears:

![image](https://user-images.githubusercontent.com/3083270/64924314-1f8c9180-d7b1-11e9-9684-eaa8e9a3a024.png)

I only see this on Chrome, not Safari.

**Comment by jordinl83** [comment]
@dankohn I would say there's something wrong with that [svg](https://www.cncf.io/wp-content/uploads/2017/08/aqua-security.svg). The other entries that use [hosted_logos/aqua.svg](https://github.com/cncf/landscape/blob/master/hosted_logos/aqua.svg) work fine. Can we not use [hosted_logos/aqua.svg](https://github.com/cncf/landscape/blob/master/hosted_logos/aqua.svg) for both?

Also, why is there [Aqua](https://github.com/cncf/landscape/blob/master/landscape.yml#L303-L308) and [Aqua Security (member)](https://github.com/cncf/landscape/blob/master/landscape.yml#L5637-L5640)?

**Comment by dankohn** [comment]
We often list a closed source product and a member card separately. @ZeusTheTrueGod could you please take a look at the logo?

**Comment by AndreyKozlov1984** [comment]
I'm not able to reproduce this

**Comment by jordinl83** [comment]
@AndreyKozlov1984 it does not happen all the time:

![aqua](https://user-images.githubusercontent.com/16135423/65889009-c885df80-e3a0-11e9-894b-827b8414f5b9.gif)

**Comment by dankohn** [comment]
@jordinl83 Could you take this?

**Comment by jordinl83** [comment]
@dankohn @AndreyKozlov1984 giving it a 2nd try

**Comment by jordinl83** [comment]
@dankohn this is actually quite obscure and seems to only happen on Chrome.

I created a simple HTML page to show the logo that disappears in a few different sizes:
![Screenshot 2019-10-02 at 16 31 52](https://user-images.githubusercontent.com/16135423/66054280-08310080-e534-11e9-9920-ff884371f3e6.png)

As you can see it does not show correctly for some sizes, so I though the issue was that the browser didn't know how to resize it for some widths. But then I tried to set the same width and height every time but the issue still persisted:
![Screenshot 2019-10-02 at 16 33 19](https://user-images.githubusercontent.com/16135423/66054281-08c99700-e534-11e9-95eb-7d8bcc64f9ce.png)

So the issue has nothing to do with width and height. Then I found a Stack Overflow thread that was discussing some issues with SVGs and somebody suggested that the issue could be with having the same IDs in two different SVGs. So I tried the HTML page with the different logo sizes, but instead of loading the same logo every time, load a copy of the logo with randomly generated IDs. And the problem went away:
![Screenshot 2019-10-02 at 16 43 39](https://user-images.githubusercontent.com/16135423/66054282-08c99700-e534-11e9-8540-a0efaed8cc0e.png)

Now there are a couple of options to apply this on the landscape:
1. When running `npm run update`, modify the logos so there are no ID collisions.
2. Don't process the logos with `npm run update` and instead on the front-end do an AJAX request to fetch the logo, replace the IDs of the logo and insert it in the DOM.

I would suggest going with `1.`, unless you think there is a good reason not to go with that option.

**Comment by jordinl83** [comment]
@dankohn On second thought, we could also do the ID replacement on the fly in the browser with [svg-inject](https://github.com/iconfu/svg-inject), it doesn't exactly work as advertised in their README, but with a few tweaks it does work.

**Comment by dankohn** [comment]
Nice analysis.

What are the URLs for the Stack Overflow thread? Can you please see if a Chromium bug has been filed for it?

**Comment by jordinl83** [comment]
@dankohn This is the discussion on SO: https://stackoverflow.com/questions/29924514/svg-disappear-when-zoom-in-on-chrome

My fix does not seem to fix the issue on landscape though. It works on the page I created with the repeated logo, but not on landscape...

**Comment by dankohn** [comment]
I understand why IDs need to be unique on inlined SVGs but it seems like a bug to require them to be from SVGs fetched via an img tag.

https://css-tricks.com/youre-inlining-svg-icons-deal-unique-titles-ids/
https://stackoverflow.com/questions/36777675/why-doesnt-chrome-display-svgs-with-use-and-filter-urlid-attributes

We could replace IDs with the logo title as part of our autocrop, but it doesn't seem like that should be necessary.

Could you please search for Chromium bugs, and if you can't find one, consider opening one with your HTML page as a reproducible test.

**Comment by jordinl83** [comment]
@dankohn you're right. I think there was a bug in my logic to replace the IDs, so by breaking the SVG it was somehow showing correctly in Chrome.

Haven't found a bug on Chromium that matches this issue, so I'll file a new one. I've created a small example that shows this issue, see:

* https://github.com/jordinl83/logo-bug
* https://jordinl83.github.io/logo-bug/

**Comment by jordinl83** [comment]
@dankohn also, it seems that Chrome has recurring issues with SVGs. I wonder if we could use a 3rd party image processing service to convert the SVGs to PNG, with the added benefit that we could also resize them on the fly. I've used [imgix](https://www.imgix.com) in the past and it worked very well, costing us $15/mo. In order to use SVGs with Imgix, we would need to contact support, but Cloudinary supports SVGs out of the box. Below are some examples of the resized logo as an SVG, you can play with the size by just changing the width and height in the URL:

https://res.cloudinary.com/idemo/image/upload/w_400,h_400/yvndkjvbfzufqxdldjhd.png

<code>
400x400
</code>
<table><tr><td>
<img src="https://res.cloudinary.com/idemo/image/upload/w_400,h_400/yvndkjvbfzufqxdldjhd.png" />
</td></tr></table>

<code>
400x200
</code>
<table><tr><td>
<img src="https://res.cloudinary.com/idemo/image/upload/w_400,h_200/yvndkjvbfzufqxdldjhd.png" />
</td></tr></table>

<code>
200x200
</code>
<table><tr><td>
<img src="https://res.cloudinary.com/idemo/image/upload/w_200,h_200/yvndkjvbfzufqxdldjhd.png" />
</td></tr></table>

<code>
200x100
</code>
<table><tr><td>
<img src="https://res.cloudinary.com/idemo/image/upload/w_200,h_100/yvndkjvbfzufqxdldjhd.png" />
</td></tr></table>

<code>
100x100
</code>
<table><tr><td>
<img src="https://res.cloudinary.com/idemo/image/upload/w_100,h_100/yvndkjvbfzufqxdldjhd.png" />
</td></tr></table>

**Comment by dankohn** [comment]
Love your example! Very well done. I'm sure the Chromium team will also appreciate it.

No, although I like Cloudinary, I don't want to use them. I like the fact that all of the logos we make available are in the original high-resolution format. I like that when I zoom, I can see arbitrary resolution, such as https://landscape.cncf.io/zoom=1200, without needing new images to be downloaded.

I'm optimistic that SVG support will improve in Chrome, especially if we help with a Chromium bug report.

Please link the Chromium bug here once you file it and then you can close this.

**Comment by jordinl83** [comment]
@dankohn Bug report submitted: https://bugs.chromium.org/p/chromium/issues/detail?id=1011299

**Comment by jordinl83** [comment]
@dankohn also, I've looked into how the faulty logo was generated and I'm not sure if this could be an issue with autocrop.

The logo was added in: https://github.com/cncf/landscape/pull/1201, with:

```yaml
- item:
  name: Aqua Security (member)
  homepage_url: 'https://www.aquasec.com/'
  logo: 'https://www.cncf.io/wp-content/uploads/2017/08/aqua-security.svg'
  crunchbase: 'https://www.crunchbase.com/organization/aquasecurity'
```

So the original logo is https://www.cncf.io/wp-content/uploads/2017/08/aqua-security.svg and looks like:

```svg
<svg xmlns="http://www.w3.org/2000/svg" 
     xmlns:xlink="http://www.w3.org/1999/xlink" 
     viewBox="0 0 400 245" 
     width="400" 
     height="245">
  <path fill="none" pointer-events="none" d="M0 0h400v245H0z"/>
  <g transform="matrix(.8528 0 0 .8528 .443 60.245)">
```

Running autocrop on the SVG outputs:

```svg
<svg xmlns="http://www.w3.org/2000/svg" role="img" xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0.33 57.08 399.10 131.35">
  <path fill="none" d="M0 0h400v245H0z" pointer-events="none"/>
  <g transform="translate(.443 60.245) scale(.8528)">
```

Which matches [cached_logos/aqua-security-member.svg](https://github.com/cncf/landscape/pull/1201/files#diff-338c5eaff5aed11034646cf898ed35f0) from the PR. Note that the viewbox changed.

When I try to render the original in my demo app it renders correctly:

![Screenshot 2019-10-04 at 12 30 09](https://user-images.githubusercontent.com/16135423/66201094-c2df1100-e6a2-11e9-958f-3998cfa1e05f.png)

And, as we know, when I try to render the processed SVG it does not work:

![Screenshot 2019-10-04 at 12 33 31](https://user-images.githubusercontent.com/16135423/66201247-32ed9700-e6a3-11e9-9d46-0f0466236a5e.png)

**Comment by dankohn** [comment]
I believe the custom viewbox is exposing the bug but the SVG is completely valid and so it is a real bug in Chromium, no?

**Comment by jordinl83** [comment]
@dankohn not 100% sure. I see that the Chromium team has acknowledged the bug and they say there's a fix coming up on version 79. 

I was looking for alternative ways to accomplish the same that autocrop is doing, but couldn't find a way that didn't encounter the same issue on Chrome...

**Comment by jordinl83** [comment]
@dankohn issue seems fixed
