### ISSUE TITLE
ASWF tweet count is wrong

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#344]
The ASWF tweet count shows 37 but should show 1.

https://landscape.aswf.io
https://twitter.com/search?q=https%3A%2F%2Flandscape.aswf.io&src=typd

It is probably because we copied the LF Edge website to start it.

**Comment by jordinl83** [comment]
@dankohn this count seems to be based on a [search](https://github.com/cncf/landscapeapp/blob/master/tools/calculateNumberOfTweets.js#L12) performed on [AcademySwf](https://github.com/AcademySoftwareFoundation/aswf-landscape/blob/master/settings.yml#L13).

**Comment by dankohn** [comment]
It should instead be a search for `landscape.aswf.io`.

**Comment by dankohn** [comment]
It should be using: https://github.com/AcademySoftwareFoundation/aswf-landscape/blob/master/settings.yml#L21

**Comment by jordinl83** [comment]
@dankohn actually, it seems to be using `twitter.search` from settings. But what the search is doing is fetching tweets since the [last id](https://github.com/AcademySoftwareFoundation/aswf-landscape/blob/master/processed_landscape.yml#L3479) and adding the result to the existing [count](https://github.com/AcademySoftwareFoundation/aswf-landscape/blob/master/processed_landscape.yml#L3479). So if the `count` is wrong, we can either update `processed_landscape.yml` to have `count = 1` or we will have to find an alternative way of counting tweets.

I see we're using the _Standard_ Search API, which has a 7-day archive limit, so there's no way to count all tweets with that.

But the _Premium_ Search API has access to the full-archive and it has a _counts_ endpoint:

https://developer.twitter.com/en/docs/tweets/search/overview

I wonder if we would be able to switch to the _Premium_ plan.

**Comment by dankohn** [comment]
This is by design. We didn't think it was worth paying for a premium
Twitter license as we can just compare the historic count stored in
`processed_landscape.yml` with the count since last update.

What we didn't plan for was the proliferation of landscapes. Could you
please create a script that zeroes out the Twitter count and puts in the
current timestamp, which I can run once on each new landscape so that the
count will start from zero?
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by jordinl83** [comment]
@dankohn I can totally add a script to reset the tweet count to 0. But if the use case is when creating a new landscape, wouldn't it make more sense to not copy `processed_landscape.yml`?

**Comment by dankohn** [comment]
We could, but I think a script would be clearer. Processed landscape can be really slow to regenerate from scratch.
