### ISSUE TITLE
Improve styling of card modal on small screens

### ISSUE THREAD

**Issue by jordinl83** [cncf/landscapeapp#363]
The card modal has 40px margin and 20px padding on each side on mobile, this means that on 360px wide devices, there's 120px wasted and the content is just shown in 240px.

I would suggest making the modal take the full width and height or just have some small margin on the outside. See below for how each different option would look like:

current | full width/height | 5px 
--| -- | -- 
![current](https://user-images.githubusercontent.com/16135423/65753710-cc4f0300-e10f-11e9-9a95-5082e5705c28.png) | ![0px](https://user-images.githubusercontent.com/16135423/65754113-a4ac6a80-e110-11e9-9d93-5fdd6e605aa5.png) | ![5px](https://user-images.githubusercontent.com/16135423/65753704-cbb66c80-e10f-11e9-8b67-c2a25b6cff37.png)

10px | 15px | 20px
-- | -- | --
![10px](https://user-images.githubusercontent.com/16135423/65753707-cbb66c80-e10f-11e9-838e-2d6357d21444.png) | ![15px](https://user-images.githubusercontent.com/16135423/65753708-cbb66c80-e10f-11e9-993d-29d16ae3d678.png) | ![20px](https://user-images.githubusercontent.com/16135423/65753709-cc4f0300-e10f-11e9-8f27-aa2900120f99.png)

**Comment by jordinl83** [comment]
@dankohn given there's more vertical space than horizontal, we could move the arrows to the bottom:

![ezgif-4-9927bb0b28a9](https://user-images.githubusercontent.com/16135423/65765556-dd583e00-e128-11e9-82cc-bdc1969b7da4.gif)

Alternatively, there's enough space next to the product logo, but they would have to disappear when the user scrolls:

<img src="https://user-images.githubusercontent.com/16135423/65765607-05e03800-e129-11e9-867d-c3e9479799e0.png" alt="next-to-logo" height="480"/>

**Comment by dankohn** [comment]
What do you recommend?

**Comment by jordinl83** [comment]
@dankohn placing the arrows next to the logo is definitely the most efficient use of space, I think it also looks good. So unless you want the arrows to be always visible I would go with that.

**Comment by dankohn** [comment]
OK.

**Comment by dankohn** [comment]
Unfortunately, I'm not happy with this new design and prefer the functionality of the current implementation. My issues are that:
* In the current design, the left and right arrows are always visible. I often scroll down, then click right. In the new design, I have to scroll down, then scroll up, before I can click right.
* In the current design, the `X` for closing floats above the modal and so is always accessible. In the new design, I have to scroll back to the top to access it.
* In the current design, I can dismiss by clicking on the `X` or on the margin (except where the arrows are).

Can you emulate the current design, except reducing the margins to 25px? Or should we just give up on this as one of those cases where the new design looked good but the UX turned out to be problematic?
