### ISSUE TITLE
Reset Twitter counts on new landscapes

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#369]
Please run `y reset-tweet-count` and then confirm that the regular nightly update picks up the current count (if any).

**Comment by dankohn** [comment]
After removing entry, it did not create a new entry on the next build. https://github.com/AcademySoftwareFoundation/aswf-landscape/commit/cc7b453d14f25b74dd6514407526c04d54afd336#diff-ea4f83e4d8108e8fdb17ec90794f9bdf

ASWF currently should show 1:https://twitter.com/search?f=tweets&vertical=default&q=landscape.aswf.io&src=typd

**Comment by jordinl83** [comment]
@dankohn that's because the _Standard_ Twitter Search API can only search tweets from the last 7 days: https://developer.twitter.com/en/docs/tweets/search/overview. Which means if we reset the tweet count on a landscape and there are tweets that are older than a week, those tweets won't be accounted for. That's why I was suggesting to use the _Premium_ plan, which has access to the full history and can actually perform a count.

**Comment by dankohn** [comment]
And, I said I don't want to pay. Can you please suggest a way that I can manually insert in the number of tweets to date and then have it count using the standard API going forward? That's what we did for CNCF.

**Comment by jordinl83** [comment]
@dankohn I could change `npm run reset-tweet-count` to accept one argument which would be the updated tweet count, so in this case you would execute `npm run reset-tweet-count 1`. If no count was passed, I would set it to 0.

**Comment by dankohn** [comment]
Great!

**Comment by dankohn** [comment]
And once we make that change, could you please manually run it on each of the landscapes (other than CNCF and AI, which are correct).
