### ISSUE TITLE
Speed up netlify builds

### ISSUE THREAD

**Issue by AndreyKozlov1984** [cncf/landscapeapp#379]
1. Check if we can run certain things in parallel within a single dashboard. While a webpack build can not be run in parallel, following tasks can be run in parallel:
- render landscape
- check landscape for errors
- run tests

I would run all 3 in parallel, capture stdout and stderr output and display the output in order, so logs are same and we do not have console output messed from all the 3 tasks. 

2. Look for best ways to run all our landscapes in parallel. The primary idea is that from a netlify build we then run a specific landscape build on a different machine, be it a docker instance in the cloud, CircleCI build, or whatever, capture the output and report it back to netlify. And with that  approach all 8 landscapes are ran in parallel, while netlify is used just to capture and report the output from real build servers. We should capture the output and display it independently for every landscape, like it is done right now. There are a lot of options how exactly to obtain machines where we run builds, but as I remember, the decision was Azure Pipelines, although CircleCI or using a server on package.net could also work.

@dankohn please comment

**Comment by dankohn** [comment]
https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/ allows 10 simultaneous builds while GitHub actions enables 20 https://help.github.com/en/articles/about-github-actions#usage-limits

Ideally, use the Netlify Docker image to ensure compatibility. Note that the goal is to both speed up individual builds and landscapeapp all-landscape builds.

One option is to stop using Netlify for test builds at all and just use the CI server, since they all have a way of serving artifacts. That would relate to #9 where we want the cause of fatal errors to be reported to the pull request.

**Comment by dankohn** [comment]
I had to revert because CNCF was hanging on `[Browsersync] Watching files...`
https://app.netlify.com/sites/landscape/deploys/5d9e5191075d72bbafe5ad4f

**Comment by AndreyKozlov1984** [comment]
That was done.
We are running tasks in parallel whenever possible.
We build all landscapes in parallel on our own build server.
The individual landscape is built both on a netlify instance and on our own build server in parallel.
