### ISSUE TITLE
Honor YAML multiline rules

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#396]
Note the 2 line YAML here: https://github.com/lf-energy/lfenergy-landscape/blob/master/settings.yml#L154-L155

The description next to the bar code should not have this extra return in the middle:

![image](https://user-images.githubusercontent.com/3083270/66711026-def14b00-ed51-11e9-8d16-0e64106a146a.png)

Note this it doesn't appear on https://landscape.lfenergy.org/images/landscape.png.

![image](https://user-images.githubusercontent.com/3083270/66711034-021bfa80-ed52-11e9-9511-20e0645f1a21.png)

**Comment by AndreyKozlov1984** [comment]
The problem was that we have to properly display a text when a browser zooms out, thus we use a trick with `transform: scale(0.25)` and `zoom: 400%` so the text is properly displayed during a zoom. But somehow the puppeteer does not render the pdf properly in this case, thus I had to use an old code to render a text without those transform and zoom tricks.
