### ISSUE TITLE
Fix accessibility errors

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#468]
https://tourmaline-salsa.glitch.me/
https://webhint.io/scanner/e5e3ec29-d41a-4bbb-92e0-189d3c70986b

Most of them can be fixed with alt tags and starker contrast.

**Comment by jordinl83** [comment]
There are two more additional issues on the modal page: https://webhint.io/scanner/3a54bce0-1320-4bb3-b7ee-a4d85faddd42

The **ARIA roles used must conform to valid values** error happens because the modal (from Material UI) has `role="none presentation"`.  Webhint is giving an error because multiple roles is not well supported https://github.com/dequelabs/axe-core/issues/1916. On the other hand multiple roles are actually allowed: https://www.w3.org/TR/2014/REC-wai-aria-implementation-20140320/#mapping_role

> WAI-ARIA allows multiple roles to be specified as an ordered set of space-separated valid role tokens. The additional roles are fallback roles similar to the concept of specifying multiple fonts in case the first choice font type is not supported.

The **ARIA hidden element must not contain focusable elements** happens because Material UI adds `aria-hidden=true` to elements outside the modal, but one of the `divs` with `aria-hidden=true` contains an element with `tabindex=0` which causes this error. There's an issue opened with `axe-core` discussing if this is a false positive: https://github.com/dequelabs/axe-core/issues/1482

I think there's nothing we can do to fix these right now.

**Comment by jordinl83** [comment]
Closing with https://github.com/cncf/landscapeapp/pull/484
