### ISSUE TITLE
Database vs. YAML file? Query API?

### ISSUE THREAD

**Issue by JesseAA** [cncf/landscapeapp#525]
### This is the upstream landscapeapp
:question: Are you aware if anyone has ported this to using a database vs. YAML file?

Similarly, my team has built a REST API atop the the old codebase ... is that something that's already been done, too?

**Comment by dankohn** [comment]
It's pretty trivial to load a JSON file into a database. Also note the button at the bottom left for downloading data (or the currently viewed subset) as a CSV file. I know the CSV option is relatively popular for people doing research in the space. I'm not sure I see the value of a REST API since one of the strengths of the landscape is that it's "serverless" (that is, the whole app is loaded into the browser so no server communication is necessary).

**Comment by JesseAA** [comment]
Yes, the JSON could be loaded into a database, but the app is built to use a YAML file for maintenance and during runtime. I'm curious if anyone has ported this to using a database either _instead_ of the YAML file, or as a 2ndary step, after creating the JSON file, such that the web app reads from that same database (admittedly, less valuable, but as the data.json file gets huge - I've got 1600 items now and am looking at 3000 potentially-  it might be valuable in avoiding the in-memory load of the entire file and all images).

As for the API, this was valuable in my experience because it enabled the integration of a chatbot to do queries against the landscape. I'd considered contributing this back to your upstream project if it was something valuable.

**Comment by dankohn** [comment]
Can you please describe what landscape you've built? I think we're inclined to stay with the "serverless" architecture but I'm thrilled that the project has been useful for you.

**Comment by JesseAA** [comment]
I'd like to learn more about the serverless approach you've implemented. I'm running landscape (legacy oct 2018 codebase) in Docker on OpenShift, doing "clean" builds from github with Jenkins using no cache. The desire to build "clean" all the time has resulted in frequent rate limit issues with github, even after implementing authenticated API calls. Since i've needed to add many more attributes to each tech and allow for tech to be in multiple categories, the old codebase is easier to maintain. I'm happy to share more about my implementation.

on the topic of database, the challenge i run into is PRs against a 34,000 line YAML file. My Issue was about opportunities to use a database instead of a yaml file, where Landscape build process would work as-is, but use the database to read landscape, processed_landscape data, and the UI would ultimately read data.json **data** from the db vs data.json itself.

**Comment by dankohn** [comment]
Our biggest landscape is 8.9k lines https://github.com/cncf/landscape/blob/master/landscape.yml. The processed_landscape version with data looked up is 94k.

I would encourage you to give the master of landscapeapp a try because we've made a ton of improvements over the last 18 months. Since we run most things from cache, we don't hit GitHub or other lookup limits. I can easily do an update from my laptop without needing any special infrastructure.

Also, we *just* added the functionality of replacing Crunchbase data with a manually added organization, which would allow you to avoid needing a license from Crunchbase. See https://github.com/lfph/lfph-landscape/blob/master/landscape.yml#L404-L407.

I'm going to close this issue, but please feel free to keep chatting here, or to open other issues or pull requests if we can be of assistance.

**Comment by JesseAA** [comment]
thanks, @dankohn . I did take a stab at upgrading a few months ago and didn't make much progress due to my own poor understanding of how the new settings file needs to be structured. 

Despite that, I've added half-a-dozen new attributes to each technology title, which requires modification to the source code. With the new landscape app, the upstream "engine" needs to be modified to accommodate this, requiring me to fork it, then pretty regularly update from your repo ... i'm leary about the continual maintenance that would require. Have you considered adding that kind of extensibility into the module to allow users to add their own attributes without modifying the engine?

**Comment by dankohn** [comment]
I'm not opposed in principle to adding optional parameters, but we do have a bunch of other items https://github.com/cncf/landscapeapp/projects/1 that would probably be higher priority.

Could you please share your landscape and the other parameters you're tracking so I could understand what you're looking for?

**Comment by JesseAA** [comment]
Here's some customizations made:

- 3 levels of categories/nesting vs. just 2
- titles can be in more than 1 category
- integration with GitHub Enterprise (on-premise) as a valid repo_url
- use Express.js for HTTP server and REST query API
- Added additional attributes:
  - environment: - <runtime environment/platform this tech is best suited for>
  - market: <commercial | enterprise | federal>
  - additional_info_url: <internal community of practice web site>
  - collaboration_url: <internal community of practices chat/group channel>

**Comment by dankohn** [comment]
Sounds like you might be happier sticking with your fork. We've found 2 levels of categories to be plenty. We've explicitly avoided allowing multiple categories to avoid a combinatorial explosion. We want to have things in public repos as we get a lot of useful info from GitHub.

But, I'm very glad to hear that the original code was useful.
