### ISSUE TITLE
switch from npm ci to npm install

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#569]
Please reevaluate how we can avoid reinstalling every NPM package on every build. If the issue is sharp, can we pre-install sharp as a first step? Could we replace sharp with puppeteer or similar?

We'd like Nelify's cache of npm modules to, on the happy path, be usable on the next build, assuming only the content has changed.

**Comment by AndreyKozlov1984** [comment]
Ok, let's do a standard `npm install`26.05.2020, 22:27, "Dan Kohn" <notifications@github.com>:
Please reevaluate how we can avoid reinstalling every NPM package on every build. If the issue is sharp, can we pre-install sharp as a first step? Could we replace sharp with puppeteer or similar?
We'd like Nelify's cache of npm modules to, on the happy path, be usable on the next build, assuming only the content has changed.

**Comment by jordinl83** [comment]
Don't think this is a trivial task. If there are issues with Sharp I would fix those first, I haven't had any issues with Sharp. 

Also, I recommended switching to yarn, which takes 50 seconds instead of 3 minutes for npm on my machine: https://github.com/cncf/landscapeapp/pull/546

I would also recommend trying to reduce the number of dependencies we have.

**Comment by dankohn** [comment]
I'm open to switching back to yarn if the problems we ran into before have been resolved. However 50 seconds, can't compare to 0, which is what it should take most of the time if Netlify were properly able to cache the node_modules directory.

**Comment by AndreyKozlov1984** [comment]
I also like yarn, need to compare if it is any faster.28.05.2020, 15:05, "Jordi Noguera" <notifications@github.com>:
Don't think this is a trivial task. If there are issues with Sharp I would fix those first, I haven't had any issues with Sharp.
Also, I recommended switching to yarn, which takes 50 seconds instead of 3 minutes for npm on my machine: #546
I would also recommend trying to reduce the number of dependencies we have.

**Comment by AndreyKozlov1984** [comment]
That was done, 
When we upgrade to a new version of node.js, that is a very rare event, we use npm install from scratch
When we have a new package for the first time, we run `npm install` on a cached copy of node_modules from the master branch

Finally, what we have almost every time, when there is a cache for a give combination of node version, package.json, and npm-shrinkwrap - we just use an existing copy of node_modules with everything already installed.
