### ISSUE TITLE
Add visual regression tool

### ISSUE THREAD

**Issue by dankohn** [cncf/landscapeapp#94]
Integrate into workflow to ensure that all visual changes are intended. This would be particularly useful when updating dependencies.

https://github.com/garris/BackstopJS

**Comment by ZeusTheTrueGod** [comment]
Overall, I've researched two approaches: using a backdropjs and using jest-image-snapshot.

Backdropjs is just a nice wrapper around taking screenshots, but it allows only one screenshot per test, thus it will take way more time to run complex tests, and to me looks like something we do not need at all.

Taking screenshots via jest-image-snapshot or jest-screenshot take some time, I think the test became 2-3 times slower, i.e. 180s instead of 60s. 
Next, there are false positives in rendering SVG files and in rendering on different platforms.
Of course, we need to wait 5-10 seconds to ensure that all images/resources have been loaded or even completely disable loading images.
What also bothers me is that we need to run a test on a certain commit of cncf and lfdl landscapes, and then run it weekly and manually review images to ensure that all works well on latest commits

The main advantage is that we can ensure that there are really no regression because of our changes - i.e. different colors, problems with devices, etc.

**Comment by dankohn** [comment]
Closing for now. We may revisit.
